# Memory Module Configuration
memory: 
  closed_vocabulary: True
  vocabulary: 
    - Personnalité
    - Intérêts
    - Emploi
    - Education
    - Famille
    - Relations
    - Loisirs
    - Santé
    - Emploi_du_temps
    - Habitudes
    - Alimentation

#llm configuration
reply-llm:
  model: "gpt-4o"
  temperature: 0.7
  max_tokens: -1
memory-llm:
  model: "gpt-4o"
  temperature: 0.7
  max_tokens: -1